package com.syvlabs.organizr.model.db.objects;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "ENTRY".
 */
public class Entry {

    private Long id;
    private String title;
    private String content;
    private Boolean done;
    private Integer type;
    private Integer color;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Entry() {
    }

    public Entry(Long id) {
        this.id = id;
    }

    public Entry(Long id, String title, String content, Boolean done, Integer type, Integer color) {
        this.id = id;
        this.title = title;
        this.content = content;
        this.done = done;
        this.type = type;
        this.color = color;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public Boolean getDone() {
        return done;
    }

    public void setDone(Boolean done) {
        this.done = done;
    }

    public Integer getType() {
        return type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

    public Integer getColor() {
        return color;
    }

    public void setColor(Integer color) {
        this.color = color;
    }

    // KEEP METHODS - put your custom methods here
    public boolean isNew() {
        if (getId() == null)
            return true;
        return getId() < 0;
    }
    // KEEP METHODS END

}
